### ISSUE TITLE
[Question] Web Hosting

### ISSUE THREAD

**Issue by CubeCoding77** [Willard21/MineKhan#100]
Hi Willard, 
I was wondering which web server host you are using to host yor website. I was also wondering how you are able to ban users using their ip.

**Comment by Willard21** [comment]
It's not a "web server host", but I'm using "IONOS" as a VPS. Basically it's a remote computer running ubuntu-server that I can SSH into with the command line. I use Contabo at work and it's cheaper with better hardware, but I had to do a bit more configuration to get it to work. I would switch willard.fun to that, but it would take a few hours, and I haven't felt like it. As for how I IP ban users, I say
```js
if (banned[req.ip]) {
    res.status(401).send("Banned lol")
    return
}
```
(I keep an in-memory copy of banned IPs for speed, as well as a database table with them for persistence)

**Comment by CubeCoding77** [comment]
Oh ok, Thanks
