### ISSUE TITLE
Generation issue

### ISSUE THREAD

**Issue by Skywalker1235** [Willard21/MineKhan#107]
anytime when I spawn on an island I'm always covered in something like an iron clay or other block could you please fix it
Versions: 1.0.5 and 1.0.4  1.0.3

**Comment by sauron65** [comment]
That is thingMaker's MineKhan. This is the original, much faster, Willard's MineKhan. Willard's MineKhan is at Alpha 0.7.1

**Comment by harsha7addanki** [comment]
first of all lets just close  this issue
