### ISSUE TITLE
The Far Lands???

### ISSUE THREAD

**Issue by ebp012** [Willard21/MineKhan#110]
I teleported 12.6 million blocks out, and the structure of the game is completely broken. Block hitboxes don't work, blocks aren't perfect cubes at all anymore, and the camera is disconnected from the player, but you can still move, though it sometimes goes blank and flashes really hard. Only occasionally a visible landscape appears.
<img width="2514" alt="Screenshot 2023-01-02 at 7 17 40 AM" src="https://user-images.githubusercontent.com/96751029/210544982-56790931-c2da-41a3-80fb-df8848926daf.png">

**Comment by Low-Fat-Lard** [comment]
This is the wrong minekhan

**Comment by Willard21** [comment]
All versions have the same problem. The coordinates are computed GPU-side, so there's not enough floating point precision to handle going that far from spawn. But my version doesn't have a teleport command, so it's not practical to go that far away, so I'll close this.
