### ISSUE TITLE
hii

### ISSUE THREAD

**Issue by csf44033** [Willard21/MineKhan#135]
hello :3

**Comment by Willard21** [comment]
Hi

**Comment by danerjin** [comment]
can we add an entities framework, and jsut start with cube mobs, im thinking of camman18's 'minecraft, but blocks attack you
https://www.youtube.com/shorts/WL5AfI0JJQk

**Comment by Willard21** [comment]
Floating cube entities already exist. That's how I render players in multiplayer.
