### ISSUE TITLE
Servers Possible But Not Added?

### ISSUE THREAD

**Issue by harsha7addanki** [Willard21/MineKhan#17]
Servers Are Possible With CORS So Why Not Try It 😀
Note: I Am The One Who Said The Is 1000 X Better Than 2d benniums Version

**Comment by InterestingBrainPoops** [comment]
There is no multiplayer support made
So there would be no need for adding servers

**Comment by harsha7addanki** [comment]
point but multiplsyer is gooood

**Comment by Elite230** [comment]
it will be cool if willard develops a way to create servers - even if that requires paying him for it.

**Comment by CorruptedKarma** [comment]
even if he creates servers he can't make multiplayer sadly

**Comment by Extex101** [comment]
**Laughs in Multiplayer**

**Comment by harsha7addanki** [comment]
Oh Yeah Showing Players And Names But There Are No Names

**Comment by Extex101** [comment]
![Hmm](https://cdn.discordapp.com/attachments/731003852970524715/829474113491697684/Screenshot_at_2021-04-07_14-50-48.png)

**Comment by Hacker1254** [comment]
is there a way to add Multiplayer, plus looking at the new update they added something new, 
![image](https://user-images.githubusercontent.com/69991448/114394807-9e9ea300-9b69-11eb-9ab5-32a4282ab3bf.png)

**Comment by CrimsonCodes0** [comment]
@CorruptedKarma's comment was completely unfounded, multi-player is completely possible, and they added the beginnings of multi-player support yesterday, see https://github.com/Willard21/MineKhan/pull/20#issuecomment-817360803.

**Comment by Hacker1254** [comment]
Hell yes!

**Comment by CorruptedKarma** [comment]
No I know that I was playing it but I was talking about on khan academy

**Comment by CorruptedKarma** [comment]
Someone could close this issue because they're created now

**Comment by Willard21** [comment]
Sure why not

**Comment by InterestingBrainPoops** [comment]
> No I know that I was playing it but I was talking about on khan academy

im pretty sure khan does something with blocking external connections (websockets, etc), but I might be completely wrong.

**Comment by Willard21** [comment]
It's called the Content Security Policy. It's basically a connection whitelist. Since that's enabled, it's impossible to connect to any domain except khanacademy.org and kasandbox.org from inside the sandbox. People have found ways to abuse KA's API to send data around, but that'll most certainly be patched once the KA devs realize it's a higher priority than their migration project.
