### ISSUE TITLE
Adding .SCH Support

### ISSUE THREAD

**Issue by Hacker1254** [Willard21/MineKhan#22]
there are a few .SCH Worlds from 
cubical.xyz than i think will be cool in MineKhan 
[Rename ME to file.schematic.txt](https://github.com/Willard21/MineKhan/files/6312426/Rename.ME.to.schematic.txt)

**Comment by Willard21** [comment]
Huh, I didn't know that existed. But no for 2 reasons. 
1: It looks like it stores files in binary format. Figuring out how to parse that would be a nightmare.
2: It has lots of blocks that MineKhan doesn't, so there's no way to do a 1 to 1 block conversion.

**Comment by Hacker1254** [comment]
ah ok thanks 👍

**Comment by CrimsonCodes0** [comment]
Binary files are generally *easier* to parse than textual files, and are generally better structured.
