### ISSUE TITLE
Fix Slabs

### ISSUE THREAD

**Issue by Hacker1254** [Willard21/MineKhan#23]
![image](https://user-images.githubusercontent.com/69991448/114757797-4a8eec80-9d2a-11eb-8d38-d5d851b972c5.png)

**Comment by CorruptedKarma** [comment]
Oh @Hacker1254 is it because of all of the black shadows?? bcz that also happens to stairs

**Comment by Hacker1254** [comment]
Slabs are see-thru

**Comment by CrimsonCodes0** [comment]
Is this a regression? I.e., did this occur recently?

**Comment by Willard21** [comment]
The dark faces are new with lighting, but the see-thru faces have been around since I added stairs. I'm not sure how to reproduce consistently since it only happens on load, and only in some places (depending on chunk load order). Haven't looked into it very hard though.

**Comment by CrimsonCodes0** [comment]
Oh, I just hadn't experienced it myself, at least, not yet.

**Comment by Hacker1254** [comment]
> The dark faces are new with lighting, but the see-thru faces have been around since I added stairs. I'm not sure how to reproduce consistently since it only happens on load, and only in some places (depending on chunk load order). Haven't looked into it very hard though.
> 
> The dark faces are a simple fix. Just haven't gotten to it yet.

it happens every time i enter my world
ican paste the world code here

**Comment by Hacker1254** [comment]
here is the save code, but i have found a fix, by using a modded ver of you app it removed the lightning, it turn by fixing it, but its not a good fix 
![image](https://user-images.githubusercontent.com/69991448/115278589-a0d9a200-a113-11eb-9a1b-70dd417b4ef8.png)
![image](https://user-images.githubusercontent.com/69991448/115278595-a2a36580-a113-11eb-851c-27b23c2c0820.png)
[Save Code.txt](https://github.com/Willard21/MineKhan/files/6337975/Save.Code.txt)

**Comment by Hacker1254** [comment]
Even tho most of the lighing is gone 
its so much better

**Comment by CrimsonCodes0** [comment]
Perhaps you could put your modifications in a PR?

**Comment by Hacker1254** [comment]
ok 


https://filebin.net/k405ggtuky2o3umx/Minecraft.html?t=60ob4ogt
download https://filebin.net/k405ggtuky2o3umx/Minecraft.html

**Comment by Hacker1254** [comment]
oh you ment a pull request
Sorry

**Comment by CrimsonCodes0** [comment]
@Hacker1254 Well... it wouldn't hurt to learn.

It's harder to contribute to open-source projects on GutHub without making PR's, than it is to learn how to make a PR.

**Comment by CorruptedKarma** [comment]
What's the save code I want to see

**Comment by Hacker1254** [comment]
https://github.com/Willard21/MineKhan/files/6337975/Save.Code.txt

**Comment by Hacker1254** [comment]
its not yet done

**Comment by CorruptedKarma** [comment]
oh okay

**Comment by CorruptedKarma** [comment]
here's another 
![Uploading image.png…]()
