### ISSUE TITLE
Water Error

### ISSUE THREAD

**Issue by SnehasishCodez** [Willard21/MineKhan#28]
<!DOCTYPE html>

<html>
	<head>
		<meta charset="utf-8">
		<title>Minekhan(with biomes)</title>
	</head>
	<style>

		body {
			overflow: hidden; /* Hide scrollbars */
		}
		.world-select {
			width: 99vw;
			min-width: 300px;
			height: calc(100vh - 220px);
			position: absolute;
			bottom: 120px;
			overflow-y: auto;
			background-color: RGBA(0, 0, 0, 0.6);
			justify-content: center;
			margin: 0 auto;
		}
		.world {
			width: 250px;
			height: auto;
			border: 1px solid black;
			font-size: 18px;
      font-family: monospace;
			color: rgb(180, 180, 180);
			margin: 0 auto;
			margin-top: 15px;
			padding: 5px;
			cursor: pointer;
		}
		strong {
			color: white;
		}
		.selected {
			border: 3px solid white;
			padding: 3px;
		}
		input[type=text] {
			background-color: black;
			caret-color: white;
			border: 2px solid gray;
			color: white;
			font-size: 24px;
			padding-left: 12px;
		}
		input[type=text]:focus {
			border: 2px solid lightgray;
		}
		#boxcentertop {
      font-family: Minecraftia;
			z-index: 1;
			width: 80vw;
			max-width: 400px;
			height: 50px;
			position: relative;
			top: 30px;
			display: block;
			margin: 0 auto;
		}
		.hidden {
			display: none !important;
			font-family: monospace;

		}
		#onhover {
			background-color: rgba(0, 0, 0, 0.9);
			color: rgb(200, 200, 200);
			font-family: monospace;
			word-wrap: normal;
			width: auto;
			max-width: 400px;
			position: absolute;
			z-index: 1;
			padding: 10px;
			cursor: default;
		}
		#quota {
      font-family: Minecraftia;
			display: block;
			position: absolute;
			width: 99vw;
			margin: 0 auto;
			bottom: 110px;
			z-index: 1;
			background-color: RGBA(0, 0, 0, 0.6);
			justify-content: center;
			text-align: center;
			color: white;
		}
		#savebox{
			font-family: monospace;
		}
        @keyframes success {
  5% {
    transform: translate(0px, -7px) rotateY(100deg);
  }
  30% {
    transform: translate(0px, -24px) rotateY(-100deg);
  }
  55% {
    transform: translate(0px, -67px) rotateY(100deg);
  }
 
  60% {
    transform: rotateY(-100deg) scale(1.1, .9);
  }
  70% {
    transform: rotate(5deg);

CODE ABOVE NEEDS TO BE FIXED FROM FOLLOWING PROJECT

https://www.khanacademy.org/computer-programming/geekypeoplecraft/4805420559319040

**Comment by Willard21** [comment]
That's not my project and has nothing to do with this repo.
