### ISSUE TITLE
Better Foliac In MineKhan

### ISSUE THREAD

**Issue by SnehasishCodez** [Willard21/MineKhan#31]
https://www.khanacademy.org/computer-programming/minekhan-with-plants/6313230061223936

In this spin off the flowers and grass are actaully not solid blocks so they good :)

**Comment by Hacker1254** [comment]
strange, this is very similar to my flower code

**Comment by GuineaPigBridge** [comment]
yes

**Comment by SnehasishCodez** [comment]
ok

**Comment by SnehasishCodez** [comment]
I think willard is already working on grass and flowers so yah 👍

**Comment by Hacker1254** [comment]
i have fully added it, with no bugs

**Comment by SnehasishCodez** [comment]
> i have fully added it, with no bugs

👍

**Comment by RedMonster2** [comment]
oh hello, i just discovered this thread, it's nice to see that my mods are travelling across websites :)
