### ISSUE TITLE
Gaming in MineKhan

### ISSUE THREAD

**Issue by SnehasishCodez** [Willard21/MineKhan#34]
is MineKhan actually good for playing ???

NOT in a bad way JUST in a way of the game intriguing audience

**Comment by Hacker1254** [comment]
what kind of question is that?
OF COURSE

**Comment by SnehasishCodez** [comment]
> what kind of question is that?
> OF COURSE IT IS

You misunderstood me I mean when fall damage or weapons I dont know , those get add in server good be more fun like HYPIXEL if you know what that is.

**Comment by G7Project** [comment]
Still is a bit in dev for say but yeah other than that it is fine. Could maybe be pushed quite a bit faster performance wise...

**Comment by GuineaPigBridge** [comment]
What the actual.... this issue should be deleted

**Comment by Willard21** [comment]
No. You'll get bored immediately.
