### ISSUE TITLE
How do I ban people on willard.fun

### ISSUE THREAD

**Issue by thingMake** [Willard21/MineKhan#36]
How do I ban annoying people that keep breaking things in my world?

**Comment by GuineaPigBridge** [comment]
You type 
```
ban("username")
```
in the dev console.

**Comment by thingMake** [comment]
I tried it but it doesn't do anything.

**Comment by DiamondCoder1000** [comment]
Yeah some people are just trolls

**Comment by magic4792** [comment]
@thingMake I know how you feel, dealing with griefers (that's what I call them).  I wish there was a way for the host to remove a member of the world, but it would take a long time for Willard to code.

Another simple way to keep away major damage is to save the world often to your browser, and if someone starts breaking (griefing) in your world, you can press Esc, then the button that says Exit without saving.  You can also use the new chat feature by pressing T, and typing a message.  When ready to send, press Enter on your keyboard.  You may just be lucky enough to talk the person out of it.  This doesn't work sometimes, though.  If you have a good memory, you also may be able to remember who  griefs worlds, and hopefully use the first method I mentioned if they join, and before they do any damage.

Okay, I just wrote a lot XD - Hope I helped a bit!

**Comment by magic4792** [comment]
> You type
> 
> ```
> ban("username")
> ```
> 
> in the dev console.

May I ask how to access the dev console?

**Comment by Willard21** [comment]
F12 or Ctrl + Shift + J or Ctrl + Shift + i or through the "more tools" button in Chrome's GUI settings menu.

**Comment by SuperNova841** [comment]
Now that the /ban function exists, shouldn't this issue be closed?

P.S. to those who don't know how to use it, type /ban, a space, and then the exact username of the griefer.

**Comment by Willard21** [comment]
Oh yeah I forgot I added that this weekend lol. Yeah I'll close it.
