### ISSUE TITLE
Lock multiplayer worlds

### ISSUE THREAD

**Issue by sauron65** [Willard21/MineKhan#37]
can you add either a button to lock a multiplayer world so no more people can get in or multiplayer wolds with passwords? people keep on coming into me and my friend's world and destroying everything.

**Comment by thingMake** [comment]
When someone joins, just ban them and they can't join anymore.

**Comment by sauron65** [comment]
I tried that and it didn't work

**Comment by SnehasishCodez** [comment]
> You can play on my multiplayer minekhan: https://minekhan.thingmaker.repl.co
> It won't have any other people using it.

OMG dude that is actually the best survival remix I have ever seen !

**Comment by magic4792** [comment]
> You can play on my multiplayer minekhan: https://minekhan.thingmaker.repl.co
> It won't have any other people using it.

I don't get what you mean.  From what I read, it's multiplyer but no one will be using it?  that's basically singleplayer being falsely advertised.  I'm confused.

**Comment by BrendaPuckle** [comment]
> can you add either a button to lock a multiplayer world so no more people can get in or multiplayer wolds with passwords? people keep on coming into me and my friend's world and destroying everything.

That  happened to me too

**Comment by thingMake** [comment]
Maybe now it will have people using it.
It looks like people only play multiplayer in the morning.

**Comment by thingMake** [comment]
> You can play on my multiplayer minekhan: https://minekhan.thingmaker.repl.co
> It won't have any other people using it.

I mean it won't have a lot of people using it.

**Comment by Willard21** [comment]
This has been implemented with passwords.
