### ISSUE TITLE
How do I chat on willard.fun?

### ISSUE THREAD

**Issue by kilgorezer** [Willard21/MineKhan#39]
How do I chat on willard.fun?

**Comment by sauron65** [comment]
Currently there isn't a way to do that. If I knew were the source code was for the `WebSocket severs`, I might make a PR adding it, but currently, all you can do is build words out of regular blocks.

**Comment by thingMake** [comment]
This one has a chat in the game: https://minekhan.thingmaker.repl.co

**Comment by sauron65** [comment]
@thingMake, can you add signs to your 
MineKhan?

**Comment by SnehasishCodez** [comment]
> This one has a chat in the game: https://minekhan.thingmaker.repl.co
> 
> And a blockTxt mod (paste into console): https://drive.google.com/file/d/12GYsYEfgcvUu-4TTgIwB2u7IrgZaX-PN/view?usp=sharing
> To use blockTxt put this into the console: `blockTxt("your text here")`
> blockTxt arguments: `blockTxt(text, block, background block)`
> Note: If you use it, you can be banned for api abuse so don't use it on multiplayer.

DUDE that's the best minekhan mod ever KUDOS to you man!
