### ISSUE TITLE
Slabs & stairs

### ISSUE THREAD

**Issue by sauron65** [Willard21/MineKhan#40]
Slabs & stairs and stairs have 2 glitches: 
1. shadows: when placing a slab/stair next to a block, this happens:
![Screenshot 2021-06-02 12 14 38](https://user-images.githubusercontent.com/72841060/120540725-da056300-c39d-11eb-968f-9170b3636f21.png)
2. saves: when loading saves this happens:
![Screenshot 2021-06-02 12 19 28](https://user-images.githubusercontent.com/72841060/120540866-028d5d00-c39e-11eb-9f27-3408ef85f259.png)

**Comment by SnehasishCodez** [comment]
Ohhh ! Nice Catch Dude !

**Comment by sauron65** [comment]
For some reason, (which might have something to do with the cause of the glitch) I had to walk away then save than go back for the second glitch to show up.

**Comment by sauron65** [comment]
@Willard21 have you seen this glitch ever?

**Comment by RedMonster2** [comment]
yeah, the second glitch only happens if the blocks aren't in the first few chunks around you when you load in

**Comment by Willard21** [comment]
K fixed. Just made them transparent.
