### ISSUE TITLE
Tools

### ISSUE THREAD

**Issue by DiamondCoder1000** [Willard21/MineKhan#41]
Can you make tools like in Minecraft pi edition? Oh and don't forget about opening doors.

**Comment by GuineaPigBridge** [comment]
DIY. We need 3d models, a game object with the z-index ( in css) with a higher value than what you will have in the screen, and all linked in the game with arrays that define tools. too hard, mate.

**Comment by SnehasishCodez** [comment]
yeah @GuineaPigBridge as a point dude ¯\_(ツ)_/¯

**Comment by magic4792** [comment]
@GuineaPigBridge Very true.

**Comment by sauron65** [comment]
from  https://minekhan.thingmaker.repl.co/ s source code:
> ```
>
>//People, if you want cows, you need to put this in the console: world.entities.push(new Cow(p2.x, p2.y, p2.z))
>
>//I'm probaly not going to keep working on this.
>//Too hard
>class Cow extends Entity{
>```
I don't think the cows on it will be finished :(

But, I might finish it in the future :)

**Comment by DiamondCoder1000** [comment]
yeah

**Comment by DiamondCoder1000** [comment]
wait, are you sup6666?

**Comment by DiamondCoder1000** [comment]
I kinda fully dropped willard.fun and now use thingmaker's minekhan

**Comment by GuineaPigBridge** [comment]
You! HOW COULD YOU FORGET THE CREATOR!

**Comment by sauron65** [comment]
@DiamondCoder1000
> wait, are you sup6666?
yes I am, are you Roger999?

**Comment by DiamondCoder1000** [comment]
Yeah I'm Roger999

**Comment by DiamondCoder1000** [comment]
> You! HOW COULD YOU FORGET THE CREATOR!
It doesn't have survival,  or the nether and stuff like tht

**Comment by DiamondCoder1000** [comment]
> You! HOW COULD YOU FORGET THE CREATOR!

It doesn't have survival or the nether or stuff like tht

**Comment by DiamondCoder1000** [comment]
@GuineaPigBridge 

> You! HOW COULD YOU FORGET THE CREATOR!

It doesn't have survival or the nether or stuff like tht

**Comment by DiamondCoder1000** [comment]
@GuineaPigBridge 

> You! HOW COULD YOU FORGET THE CREATOR!

It doesn't have survival or the nether or stuff like tht

**Comment by DiamondCoder1000** [comment]
Anyway, my notifs on thingmakers "forum" is kinda quiet, wonder why...

**Comment by DiamondCoder1000** [comment]
@GuineaPigBridge 
I didn't forget, I'm just not playing his version anymore

**Comment by DiamondCoder1000** [comment]
@sauron65 
> DIY. We need 3d models, a game object with the z-index ( in css) with a higher value than what you will have in the screen, and all linked in the game with arrays that define tools. too hard, mate.

I'm not much of a js coder
I'm a python one

**Comment by magic4792** [comment]
willard.fun is the original, so I play willard.fun. I've tried thingmaker's and from what i've seen it's basically just willard.fun with a different multiplayer login and around 20 downloadable worlds.  I know willard.fun has less features, but it supports the original creator.

And, if anyone wants to know, or even cares, my willard.fun username is also magic4792.

**Comment by DiamondCoder1000** [comment]
@magic4792 
I know It's the original but like I said, it doesn't have survival or the nether.
It doesn't have sound either.

**Comment by magic4792** [comment]
> @magic4792
> I know It's the original but like I said, it doesn't have survival or the nether.
> It doesn't have sound either. Thingmaker's also has a small "forum" ([https://www.thingmaker.repl.co/website/website.html](url)) where people can suggest additions and point out bugs.

I'm aware that Thingmaker has many more features than willard.fun.  Then again, I don't wanna argue about something like this, so I'm not gonna say more than this.

**Comment by GuineaPigBridge** [comment]
magic has a point there.

**Comment by DiamondCoder1000** [comment]
@magic4792 
I'm closing this anyway
