### ISSUE TITLE
Willard.fun chat hack

### ISSUE THREAD

**Issue by magic4792** [Willard21/MineKhan#43]
Whenever I press T and then Esc in the home menu, the chat opens and closes, and if I press esc a couple more times, I get the Paused menu minus a bunch of buttons.  I need to restart the webpage to escape that menu.  It also happens in the Worlds menu.  I'm a terrible coder, but would something like
`if (inWorld && World.multiplayer=true && KeyIsPressed && keyPressed=T)
{
//chat code here
};` 
work?  
I discovered this purely by accident, but it seems strange to me.  I'm not sure if the chat messages sent in these menus can be seen by players in other worlds.

Screenshots:
![Screenshot 2021-06-10 12 42 17 PM](https://user-images.githubusercontent.com/85684044/121572135-74425800-c9e9-11eb-80fb-29d941bee577.png)
![Screenshot 2021-06-10 12 42 56 PM](https://user-images.githubusercontent.com/85684044/121572132-73a9c180-c9e9-11eb-8582-89cc920b9d3d.png)

**Comment by SnehasishCodez** [comment]
> Whenever I press T and then Esc in the home menu, the chat opens and closes, and if I press esc a couple more times, I get the Paused menu minus a bunch of buttons. I need to restart the webpage to escape that menu. It also happens in the Worlds menu. I'm a terrible coder, but would something like
> `if (inWorld && World.multiplayer=true && KeyIsPressed && keyPressed=T) { //chat code here };`
> work?
> I discovered this purely by accident, but it seems strange to me. I'm not sure if the chat messages sent in these menus can be seen by players in other worlds.
> 
> Screenshots:
> ![Screenshot 2021-06-10 12 42 17 PM](https://user-images.githubusercontent.com/85684044/121572135-74425800-c9e9-11eb-80fb-29d941bee577.png)
> ![Screenshot 2021-06-10 12 42 56 PM](https://user-images.githubusercontent.com/85684044/121572132-73a9c180-c9e9-11eb-8582-89cc920b9d3d.png)

Is this something you added to willard.fun or was it there before

**Comment by sauron65** [comment]
@magic4792
the code you put would do the opposite of what's expected because it uses the assignment operator (`=`) instead of the equality operator (`==`) or strict equality operator (`===`)
also, checking if something is equal to true doesn't need an operator because `if` statements just run the code if the expression inside converted to a `Boolean` is true.
something like this might work:
```js
if (inWorld && World.multiplayer && KeyIsPressed && keyPressed === T) {
  //chat code here 
}
```

**Comment by Willard21** [comment]
K fixed. I just needed to move the code down a couple lines.

**Comment by magic4792** [comment]
> @magic4792
> the code you put would do the opposite of what's expected because it uses the assignment operator (`=`) instead of the equality operator (`==`) or strict equality operator (`===`)
> also, checking if something is equal to true doesn't need an operator because `if` statements just run the code if the expression inside converted to a `Boolean` is true.
> something like this might work:
> 
> ```js
> if (inWorld && World.multiplayer && KeyIsPressed && keyPressed === T) {
>   //chat code here 
> }
> ```

THANKS SO MUCH :>
Yeah, I'm a bad coder, thanks for this mini-tutorial.  I mainly wanted to get the point across, not be grammatically correct (in terms of code of course)

Still, you learn something new every day!  Thanks for explaining!

**Comment by magic4792** [comment]
> > Whenever I press T and then Esc in the home menu, the chat opens and closes, and if I press esc a couple more times, I get the Paused menu minus a bunch of buttons. I need to restart the webpage to escape that menu. It also happens in the Worlds menu. I'm a terrible coder, but would something like
> > `if (inWorld && World.multiplayer=true && KeyIsPressed && keyPressed=T) { //chat code here };`
> > work?
> > I discovered this purely by accident, but it seems strange to me. I'm not sure if the chat messages sent in these menus can be seen by players in other worlds.
> > Screenshots:
> > ![Screenshot 2021-06-10 12 42 17 PM](https://user-images.githubusercontent.com/85684044/121572135-74425800-c9e9-11eb-80fb-29d941bee577.png)
> > ![Screenshot 2021-06-10 12 42 56 PM](https://user-images.githubusercontent.com/85684044/121572132-73a9c180-c9e9-11eb-8582-89cc920b9d3d.png)
> 
> Is this something you added to willard.fun or was it there before

This was there before. Found it purely by accident.
