### ISSUE TITLE
Minor thing

### ISSUE THREAD

**Issue by magic4792** [Willard21/MineKhan#46]
Okay, I'm a bit of a perfectionist here, but when I press Ctrl-U to see the view source for controls (since I always forget) it still says this in the comments at the beginning of the code:
`
T: Reload textures
`

I know that T actually accesses chat, could you fix that?  It's the most minor thing, so now I feel bad, but I posted this anyway :/

**Comment by Willard21** [comment]
Not gonna lie, I didn't think anyone would actually read those comments on willard.fun lol. Guess I might as well throw in that H is for Hyper Builder 😉
