### ISSUE TITLE
willard.fun/login doesn't work

### ISSUE THREAD

**Issue by thingMake** [Willard21/MineKhan#50]
I'm using a chromebook and the login and register buttons don't work. 
I looked at the code and I think the "?" is causing it to not work.
Can you fix it?

**Comment by Willard21** [comment]
You may have logged in in the middle of a restart or something. I haven't touched the front-end for the login page today, and the back-end worked just fine last time I checked. What "?" are you talking about btw?

**Comment by thingMake** [comment]
The "?" is here:
```js
document.getElementById("form").onkeydown=t=>{"enter"===t.key?.toLowerCase()&&login() ...
```
```t.key``` **_?_** ```.toLowerCase()```
The bolded and italic character is the question mark i'm talking about.

When I test it on the chromebook, it says: Unexpected token .
You can fix it like this: ```(t.key&&t.key.toLowerCase())```

**Comment by Willard21** [comment]
Oh. That's the optional chaining operator. It was added to Chrome over a year ago, and most other browsers got it too. Do Chromebooks not auto-update Chrome or something? 🤔

**Comment by thingMake** [comment]
When I check for updates for my chromebook, it says the chromebook is up to date.

**Comment by Willard21** [comment]
What's chrome://version (in the url) say?

**Comment by thingMake** [comment]
Sorry if its very messy.
<div id="logo" style="float: right; margin-left: 40px; text-align: right; width: 180px; color: rgb(0, 0, 0); font-family: Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><img src="chrome://theme/IDR_PRODUCT_LOGO"><div id="company" style="font-size: 0.7em; text-align: right;">Google LLC</div><div id="copyright" style="font-size: 0.7em; text-align: right;">Copyright 2021 Google LLC. All rights reserved.</div></div>
Google Chrome | 76.0.3809.136&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | 64497260c8d9c993ed7d38d6dc289870eef89252-refs/branch-heads/3809@{#1039}
Platform | 12239.92.1 (Official Build) stable-channel wolf
Firmware Version | Google_Wolf.4389.24.62
JavaScript | V8&nbsp;7.6.303.30
Flash | 32.0.0.465 /run/imageloader/PepperFlashPlayer/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; CrOS x86_64 12239.92.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.136 Safari/537.36
Command Line | /opt/google/chrome/chrome --ppapi-flash-path=/opt/google/chrome/pepper/libpepflashplayer.so --ppapi-flash-version=32.0.0.238 --use-gl=egl --enable-native-gpu-memory-buffers --gpu-sandbox-failures-fatal=yes --enable-logging --log-level=1 --use-cras --enable-wayland-server --user-data-dir=/home/chronos --enable-features=MachineLearningService,ChromeOSAssistant,EnableBackgroundBlur,MyFilesVolume --login-profile=user --has-chromeos-keyboard --guest-wallpaper-large=/usr/share/chromeos-assets/wallpaper/guest_large.jpg --guest-wallpaper-small=/usr/share/chromeos-assets/wallpaper/guest_small.jpg --child-wallpaper-large=/usr/share/chromeos-assets/wallpaper/child_large.jpg --child-wallpaper-small=/usr/share/chromeos-assets/wallpaper/child_small.jpg --default-wallpaper-large=/usr/share/chromeos-assets/wallpaper/oem_large.jpg --default-wallpaper-small=/usr/share/chromeos-assets/wallpaper/oem_small.jpg --default-wallpaper-is-oem --enable-consumer-kiosk --enterprise-enrollment-initial-modulus=15 --enterprise-enrollment-modulus-limit=19 --login-manager --first-exec-after-boot --vmodule=*/chrome/browser/chromeos/account_manager/*=1,*/chromeos/components/account_manager/*=1,app_list_syncable_service=1,*/chromeos/power/auto_screen_brightness/*=1,*/forced_extensions/installation_tracker*=2,extension_downloader=2,existing_user_controller=2,*/ash/wm/tablet_mode/*=1,auto_enrollment_controller=1,*/ui/ozone/*=1,*/ui/display/manager/chromeos/*=1,update_engine=1,component_updater_service=1 --enable-features=MachineLearningService,ChromeOSAssistant,EnableBackgroundBlur,MyFilesVolume --origin-trial-disabled-features=SecurePaymentConfirmation --ui-compositor-memory-limit-when-visible-mb=512
Executable Path | /opt/google/chrome/chrome
Profile Path | /home/chronos/u-99df7cdf98d8d7c88eddaf64da4876e23e35a834
Variations | d01ab0d3-377be55a414bf2d2-377be55a976622d1-2f709970591560a-391606447903da77-377be55a63bf0740-3f4a17df41c72c78-377be55a4cbcf8ef-377be55ae84c8bf2-377be55a3095aa95-3f4a17df9568c338-377be55a58546ca6-377be55a2a565533-a9ddec78e27776-377be55a8f80d469-377be55ad8e87453-516c6aad98be3390-d93a0620e4a357e9-ca7d8d80d6d4ee9a-377be55a64c5e43d-377be55a55a3035a-377be55adac832a5-377be55a2ea1f2c6-377be55a76d4cff8-12ede6a2e111fcd-3f4a17df9b4c4257-455689ed65dc5a37-377be55a43f62d3b-56dd17e7c244b7f-da2b42b9ad5dc5d-dc5e89fc2594bdf4-93d4a67a533505eb-3d47f4f4913f596c-e2062dbbe80915aa-377be55aac8d4708-377be55a3f2db1c3-7cfad6202fa8b3e1-4f7edc428d1fbf5c-5364eb6a76aafe12-377be55aed846e24-377be55a1a298d67-377be55acec9a952-ca7d8d80b8d7a428-76bcaaa6d840bbac-377be55afb57f531-377be55a1354da85-781294a7494d8760-52325d433ac60855-486e2a9c63dcb6a3-9ce370dde706e746-36a9bd45f296190c-5192b0cf4442aae2-a90023b1f690cf64-6e597edeed1d377-e1cc0f1475f0f0a0-d7f6b13ce2b18481-bca011b3e7e71889-4ad605753a8271ac-12c2269d41599a-377be55a2eb45dac-377be55a82ebe475-c7f8da8c3b6c4d49-d25a0df79ac4f12b-462f9109d7c366d2-714d46a5bc02ac9b-3f4a17df787405bb-b4c81d8762577cad-3f4a17df38878cb4-3d47f4f46f71b60a-3a65fd9a

**Comment by Willard21** [comment]
Eh sorry I just meant the first line, but Google Chrome | 76.0.3809.136 answers the question. That means your browser hasn't been updated since July 2019

**Comment by magic4792** [comment]
Yeah, I've been using a Chromebook all along, and a browser update sounds like a reasonable problem.

**Comment by Willard21** [comment]
Well I've removed the optional chaining operator. The page should work for you now. But I'd still strongly suggest updating your browser if possible. It'll help improve performance and compatibility with websites. I generally don't bother supporting older browsers since new features make development easier, and don't want to transpile my pages.
