### ISSUE TITLE
Program on Khan Academy has too many spin-offs

### ISSUE THREAD

**Issue by thingMake** [Willard21/MineKhan#53]
There are tons and tons of spin-offs that at https://khanacademy.org/computer-programming/minekhan/5647155001376768 that all don't have thumbnails and their titles are the same and they are made by the same person.
![MineKhan _ Computer programming _ Khan Academy - Google Chrome 6_22_2021 1_21_49 PM](https://user-images.githubusercontent.com/83979271/122994135-fa04c280-d35c-11eb-8b0d-a671ac41aac8.png)

Made this issue so you would know this.

**Comment by Willard21** [comment]
K
