### ISSUE TITLE
Lighting Crash

### ISSUE THREAD

**Issue by ghost** [Willard21/MineKhan#57]
So I was playing minekhan on willard.fun.
Then everything went blank.
Here is a screenshot: 
![MineKhan - Google Chrome 7_8_2021 8_42_55 PM](https://user-images.githubusercontent.com/83979271/125020315-766df580-e02d-11eb-930c-21755e2394bb.png)

**Comment by Willard21** [comment]
Was someone else in the world? I wrapped it in a try-catch to stop it from freezing from that multiplayer lighting bug, but that happens instead, so it's not a great fix lol.

**Comment by thingMake** [comment]
I wasn't in multiplayer.

**Comment by Willard21** [comment]
Oh. Were you building at the edge of ungenerated chunks or something then? 🤔

**Comment by thingMake** [comment]
I was playing around with slabs and it was nowhere near ungenerated chunks.

**Comment by thingMake** [comment]
There were also some dropped items but they were really far away.

**Comment by GuineaPigBridge** [comment]
It's prob willard. as herobrine

**Comment by thingMake** [comment]
I just joined a multiplayer world and everything was blank. It looks like the same thing as the screenshot above.

**Comment by thingMake** [comment]
I think I found out how to reproduce this bug but its not quite right. 

1. So make a 3x3 square above the ground.
2. Put a upside-down slab on one edge (not the corner)
3. Throw an item in the middle of the square.
4. If the item falls through the square, you did it right
5. Wait
6. Everything goes weird.
So if you throw more items, There will be weird things going on.

**Comment by thingMake** [comment]
Actually if you throw an item at a bunch of upside-down slabs above the ground, it will also happen

**Comment by thingMake** [comment]
There are a lot of errors in the console.

**Comment by thingMake** [comment]
I think you need to change the getlight function. Just make it so if the y is less than 1, return 0.

**Comment by Willard21** [comment]
Can you send a small world save with reproduction steps? This bug has been around for awhile, but I've only experienced it myself in multiplayer, and only very sporadically, so I haven't been able to debug it to fix it.

**Comment by thingMake** [comment]
I don't know how to reproduce the first bug. 
For the second bug, You just have to throw an item on an upside-down slab.

**Comment by thingMake** [comment]
I think this fixes the bug:
```
getLight(x, y, z, blockLight = 0) {
	if(y < 1) return 0 //<= that
	let X = (x >> 4) + this.offsetX
	let Z = (z >> 4) + this.offsetZ
	if (X < 0 || X >= this.lwidth || Z < 0 || Z >= this.lwidth) {
		return this.chunks[x >> 4][z >> 4].getLight(x & 15, y, z & 15, blockLight)
	}
	return this.loaded[X * this.lwidth + Z].getLight(x & 15, y, z & 15, blockLight)
}```

**Comment by DiamondCoder1000** [comment]
Ummm, what?

**Comment by Willard21** [comment]
Reading over this again, it appears the crash was caused by dropped items outside rendered chunks. As dropped items are gone, this _shouldn't_ be an issue any more. Hopefully.
