### ISSUE TITLE
Physics bugs

### ISSUE THREAD

**Issue by ghost** [Willard21/MineKhan#58]
So I have something like this:
![Screenshot 2021-07-14 at 12 18 31 PM](https://user-images.githubusercontent.com/83979271/125680294-00325176-b0b3-436f-9064-b1b0894cb6d1.png)
When I go to it and press w, I go up and down.

If there is a ceiling like this:
![Screenshot 2021-07-14 at 12 21 34 PM](https://user-images.githubusercontent.com/83979271/125680567-ca1f3678-570e-462b-bce2-75a41899cdd5.png)
And I jump under it, it smoothly teleports me to somewhere else.

**Comment by thingMake** [comment]
Also if i go under the ceiling and fly, I get stuck

**Comment by DiamondCoder1000** [comment]
Huh

**Comment by DiamondCoder1000** [comment]
Weird

**Comment by SnehasishCodez** [comment]
To be honest with you they should just keep this bug as it is as LOTS AND LOTS of maps and mods and parkour maps use this bug/not meant to be feature to teleport players and use it for level progression i guess willard can decide whether to keep it or not. :)

**Comment by harsha7addanki** [comment]
The Bug Should Be left intentional because after all its now the most iconic way to make elevators

**Comment by Willard21** [comment]
I've already fixed several collision bugs. I'm not going to leave in bugs on purpose, but could maybe add some sort of elevator block or something. Or maybe implement water elevators with soul sand under water like in Minecraft (although without a particle system, that's not ideal).

**Comment by harsha7addanki** [comment]
> I've already fixed several collision bugs. I'm not going to leave in bugs on purpose, but could maybe add some sort of elevator block or something. Or maybe implement water elevators with soul sand under water like in Minecraft (although without a particle system, that's not ideal).

yeah but removing this glitch could result in the breaking of many players worlds

**Comment by Willard21** [comment]
It's fine. "Elevators" are just stacks of blocks with a glitched entry method. Replacing one would take like 2 minutes tops.

**Comment by Willard21** [comment]
Fixed

**Comment by harsha7addanki** [comment]
what about players with large elevators?

**Comment by Willard21** [comment]
Here's a working elevator. Sneak onto the slab, then release it.
![image](https://github.com/Willard21/MineKhan/assets/24826881/1d3ea8db-0ff6-4bbd-a4ac-ac725a735ea0)
