### ISSUE TITLE
Item Entities Are Buggy

### ISSUE THREAD

**Issue by ghost** [Willard21/MineKhan#59]
I just threw a bunch of blocks and er..... this happened....
![2021-07-29 (2)](https://user-images.githubusercontent.com/63249054/127516076-c64da1c2-9104-457d-b9c9-0fd317f0a238.png)

**Comment by thingMake** [comment]
Probably an item went below y 0.
If that did happen, there would be a lot of errors.
So it didn't move the matrix back correctly so everything goes weird.

**Comment by Willard21** [comment]
Yeah, the last physics update causes item to clip through the ground a lot. I'll fix that soon:tm:

**Comment by GuineaPigBridge** [comment]
ok.

**Comment by Willard21** [comment]
Item entities are no longer able to be created, so this is _technically_ fixed.
