### ISSUE TITLE
Question: browser support

### ISSUE THREAD

**Issue by 00ff0000red** [Willard21/MineKhan#6]
I was checking the source, and it seems to be completely written in outdated practice.
Slapping a `"use strict"` directive on causes all of the code to fail.

I could have contributed, but was this done for browser support, or were there any other reasons?

**Comment by Willard21** [comment]
That might be a *little* over dramatic since there's only 2 lines of code that need to be fixed to work with `"use strict"` lol. 1 was from typos, and the other was from refactoring code and deleting the variable declaration on accident (but it was supposed to be global anyway so not an issue).

**Comment by 00ff0000red** [comment]
Got it, I'll probably make a few PRs soon in that case.
