### ISSUE TITLE
Players retained from previous multiplayer sessions

### ISSUE THREAD

**Issue by SuperNova841** [Willard21/MineKhan#65]
When I leave or close a server and then open one of my worlds to the public, the players from the previous world appear in their last positions, and they don't seem to be linked to the actual players' clients. I can fix it by refreshing/reloading the page, so it probably isn't the most important issue here, but if you have time...

**Comment by proudparrot2** [comment]
Wait, you can open worlds to the public?? How?

**Comment by thingMake** [comment]
You pause and press open world to public.

**Comment by Willard21** [comment]
I think this is fixed now. Probably.
