### ISSUE TITLE
Lava + icon for water

### ISSUE THREAD

**Issue by SuperNova841** [Willard21/MineKhan#66]
I think a lava block with no collisions similar to water (but with a opaque texture) would be useful in MineKhan. Also, I don't know why there isn't an icon for water, but assuming it's not too hard, could you add one (mostly so that less experienced players don't keep asking me how to get it)?

**Comment by Willard21** [comment]
I have all sorts of things I need to change about the inventory icon rendering. I'll just have to make an evening out of it one of these days. But the reason it doesn't render is because of the semi-transparent pixels.

**Comment by the-duck2010** [comment]
I think the water bug got patched today, and yesterday I submitted a pull request that adds lava. So it should be added into the master branch soon.

**Comment by Willard21** [comment]
Lava and water icons now exist.
