### ISSUE TITLE
Specifications for delays, maximum blocks per command, etc.

### ISSUE THREAD

**Issue by SuperNova841** [Willard21/MineKhan#68]
I accidentally banned myself by making a script that placed lots (thousands) of blocks, probably too fast, in my world. I set delays, but that didn't seem to work too well, so do you have any recommendations for how long I should make them? I used setTimeout with a 50 ms delay.

**Comment by Willard21** [comment]
50ms would be fine if there was no lag. I've done it with a 10ms delay without banning myself. The ban condition is 50 packets in 50ms. But if you're making mass edits like that, my recommendation would be to make the edits in singleplayer before opening the world. You can edit a million blocks without issue if it's not in multiplayer.

**Comment by SuperNova841** [comment]
What's the sleep function? I didn't see it when I searched for ways to set delays in JavaScript.

**Comment by Willard21** [comment]
It's a function I defined at the top of that code block. It just uses `setTimeout` with promises for a convenient syntax.

**Comment by SuperNova841** [comment]
Actually, I set it so that the delays increase with each iteration so they work correctly; this is the code I used.

var novaTools = {
    creator: "novacoding",
    mainDelay: 50, // milliseconds between block changes
    
    fillCube: function(x1, y1, z1, x2, y2, z2, id) {
        var xLen = x2 - x1;
        var yLen = y2 - y1;
        var zLen = z2 - z1;
        for (var i = 0; i < xLen; i++) {
            for (var j = 0; j < yLen; j++) {
                for (var k = 0; k < zLen; k++) {
                    setTimeout(
                    world.setBlock(i+x1, j+y1, k+z1, id)
                    , this.mainDelay*(i*yLen*zLen + j*zLen + k));
                    
                }
            }
        }
    },
    
    };

**Comment by Willard21** [comment]
Ah yeah, you definitely did that wrong lol. The math aside, `setTimeout` needs to be passed a function. You were just calling `setBlock` immediately and passing its return value (`undefined`) in as the callback function.

**Comment by SuperNova841** [comment]
So... the () => is what made it a function in your version, right?

**Comment by Willard21** [comment]
Correct. `const add = (a, b, c) => a + b + c` is a fancy function syntax that doesn't have its own `this` value. It's basically equivalent to
```js
let that = this;
function add(a, b, c) {
    this = that;
    return a + b + c;
}
```

In the future, I'd suggest testing that kind of thing in singleplayer first. Making your function `async` and using `await sleep(ms)` or something like that would be the easiest way to do those kinds of things cleanly.

**Comment by SuperNova841** [comment]
It works now and is showing visible delays; thanks for your help!

**Comment by Willard21** [comment]
:+1:

**Comment by SuperNova841** [comment]
When's the next server restart?

**Comment by GuineaPigBridge** [comment]
in 69 years

**Comment by SuperNova841** [comment]
lol

**Comment by SuperNova841** [comment]
Does getBlock() need to be delayed too? I want to optimize the code by only placing the block (and setting a delay) only if the block isn't already what will be placed.

**Comment by Willard21** [comment]
Nah, nah blocks are just stored locally.

**Comment by SuperNova841** [comment]
Ok, thanks! :D

**Comment by SuperNova841** [comment]
Could you restart the server? I just got banned again with a delay of 15ms from a lag spike due to someone joining :(

**Comment by Willard21** [comment]
Might I suggest just not using scripts in multiplayer? The auto-ban is in place to stop denial of service hits, since everyone is sharing the very limited resources of my VPS.

**Comment by SuperNova841** [comment]
Ok :)

**Comment by proudparrot2** [comment]
By ban, do you mean it kicks you out of the world, or it says "banned forever lol"?

**Comment by Willard21** [comment]
MineKhan bans just stop you from using multiplayer. They're temporary(ish). The "banned forever lol" bans are permanent and site-wide, so you can't even play singleplayer on the site any more. Those bans only happen when spamming the REST endpoints, or making a bunch of new accounts too fast, or trying to brute force someone's password. The rate limits are set per IP, so it's technically possible for several people on the same wifi to be using the site "normally" and exceed the limits, but for a single person, it shouldn't be possible unless they're being malicious.
