### ISSUE TITLE
Advanced Image Encoder

### ISSUE THREAD

**Issue by RedMonster2** [Willard21/MineKhan#70]
Those of us who have added other blocks to this, we have probably come across that dreaded bug where if there are to many unique colors in an image, it gets corrupted. So, is it possible, that you could make an encoder that can handle all the colors? say an encoder that can handle 256 colors?(because that's how many pixels there are in the textures) that would be so nice for those of us wanting to add things like fire, nether portal blocks, sea lanterns, prismarine..... yeah, it wouldbe nice if you could do that.

**Comment by Willard21** [comment]
~~Finished it Friday but forgot to push to upstream~~
Encoder is at https://willard.fun/minekhan/textures and decoder was just uploaded to the master branch, along with all the updated texture strings. The new encoder will crop images to the top left 16x16 pixel corner, so you can use it on animated textures to pull out the first frame. It still won't scale down bigger images.

The new decoder can apply color profiles to grayscale images, which can be used for different colored grass, leaves, and water. I haven't actually done any of those things, but I figured it could be useful in the future, or for modders.
