### ISSUE TITLE
help me and my friend

### ISSUE THREAD

**Issue by CrackersthehackerYT** [Willard21/MineKhan#72]
The is someone with a blank name who we cant ban and i really want to know if i can ban him. He greifed all of my freiend's and my hard work. Can you help me?

**Comment by ImaginaryNeon** [comment]
wow, this really is a "

![OIP (3)](https://user-images.githubusercontent.com/92883596/139673549-d0ced2e1-4f62-4f43-aea8-6a2f86440008.jpeg)

" moment.
