### ISSUE TITLE
"banned forever lol"

### ISSUE THREAD

**Issue by sunaykomarla** [Willard21/MineKhan#76]
My Latin class was using MineKhan for a latin house project, and now, a lot of peoples' websites just say "banned forever lol". I might have done something wrong, but can you please remove that? Our teacher wants to see our projects but we can't show her because of it.

I also realize that this happened before, and I didn't try to bot accounts. I am sorry if it looked like that...  Maybe it was because my classmates were all making accounts for MineKhan at the same time on the same WiFi?

 _My username is FuriousTsunami on MineKhan too._

**Comment by ImaginaryNeon** [comment]
half the names are a "Steve-colored Mario-colored Steve had a stroke reading this" moment ngl.
