### ISSUE TITLE
Private Worlds

### ISSUE THREAD

**Issue by FuriousTsunami** [Willard21/MineKhan#77]
I know I am banned, but for other users' sakes, it is possible to add a private world feature where only certain usernames can join? That would be very helpful for a lot of users who just want to build with their friends and not other people.

**Comment by ImaginaryNeon** [comment]
Wait, how tf did you manage to get BANNED??? I was banned from sm64js, but that's just cuz I posted a funny gun image. (image and comparison with original here: https://sites.google.com/online.houstonisd.org/haha-funny-gun-hand/home)

**Comment by sauron65** [comment]
#76

**Comment by proudparrot2** [comment]
#76

**Comment by Willard21** [comment]
This has now been implemented in the form of passwords. You can add a password when opening a world so only people that know it can join.
