### ISSUE TITLE
Why did productions stop?

### ISSUE THREAD

**Issue by SnehasishCodez** [Willard21/MineKhan#85]
it's been a long time since a new update :(
it's seems to be lost

**Comment by Mist-Stego** [comment]
An update can't just appear everyday, you know...

It takes a lot of time to innovate and create new things in a language like JavaScript and WebGL, so hang on while everyone keeps on creating and patching bugs.

**Comment by thingMake** [comment]
Willard probably programs it somewhere else.

**Comment by Willard21** [comment]
JavaScript is one of the easiest and fastest languages to develop in. I just haven't felt like working on it lately.
