### ISSUE TITLE
MineKhan Wiki!

### ISSUE THREAD

**Issue by proudparrot2** [Willard21/MineKhan#95]
I'm gonna make a Wiki page on Google Docs, Sites, or a GitHub repo wiki and make it as detailed as possible.

Can you make it official?

**Comment by RedMonster2** [comment]
there's already a wiki here

**Comment by proudparrot2** [comment]
I know but its not that detailed

Here it is so far: https://sites.google.com/view/minekhan-wiki

**Comment by thingMake** [comment]
There is also a wiki at: https://www.minekhan.tk/wiki

**Comment by proudparrot2** [comment]
Oh I didn't realize that...

**Comment by thingMake** [comment]
What happens when you go to the website?

**Comment by proudparrot2** [comment]
It's working now on my phone. Is it for your MineKhan or Willard's because it looks a lot like yours

**Comment by Willard21** [comment]
> I know but its not that detailed
It's a wiki because anyone (including you) can edit it to make it more detailed. You could've just edited it with the changes you wanted. Anyway I'm closing this issue. Feel free to link your wiki on the wiki instead of in an issue.
