### ISSUE TITLE
Lighting Bug

### ISSUE THREAD

**Issue by MicrolemurDev** [Willard21/MineKhan#97]
I have been playing around with MineKhan on willard.fun and have noticed a strange bug. It seems that lighting outside of chunks is not calculated when you place a 1x1 pole upwards. However, when you place and break a block on the side of that pole it fixes it.

**Screenshot:**
[https://i.postimg.cc/P5Nv378f/lightingissue.png](url)

**Console Errors:**

There are several warnings related to not enough values passed for `drawArraysInstanced` (Only 12 is passed when 16 - 24 are needed!) but other than that there aren't any console errors.

**System Info**

Firefox 97.0
KDE Neon (Ubuntu Based)
AMD RX 5500 XT on Mesa Drivers

**Comment by Willard21** [comment]
Pretty sure this is fixed now. I think the issue was new subchunks being generated with no light in them, but I've deleted subchunks now, so no longer an issue.
